import * as T from 'three';
const V=(x,y,z)=>new T.Vector3(x,y,z);
const material=(color,extra={})=>new T.MeshStandardMaterial({color,roughness:.84,...extra});
const M={plaster:material(0xe8e6dc),white:material(0xf3f0e8),shadow:material(0xb0b1a4),stone:material(0xc7c2b0),dark:material(0x272c28),glass:material(0x243331,{metalness:.24,roughness:.26}),frame:material(0x666156),curtain:material(0x999482),door:material(0x694750),wood:material(0x563b31),roof:material(0xb4674e,{side:T.DoubleSide}),ridge:material(0xc78061),gutter:material(0x827568),paver:material(0xa77e6c),asphalt:material(0x555c58),grass:material(0x607a43),earth:material(0x625741),metal:material(0x9b9481,{metalness:.6,roughness:.43})};
const noise=(a,b=0)=>{const n=Math.sin(a*127.1+b*311.7)*43758.5453;return n-Math.floor(n);};

// Merge thousands of small architectural surfaces rather than creating one draw call per tile.
class Batch {
 constructor(){this.positions=[];this.colors=[];}
 tri(a,b,c,color){for(const p of [a,b,c]){this.positions.push(...p.toArray());this.colors.push(color.r,color.g,color.b);}}
 quad(a,b,c,d,color){this.tri(a,b,c,color);this.tri(a,c,d,color);}
 mesh(parent,roughness=.9){const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(this.positions,3));g.setAttribute('color',new T.Float32BufferAttribute(this.colors,3));g.computeVertexNormals();const m=new T.Mesh(g,new T.MeshStandardMaterial({vertexColors:true,roughness,side:T.DoubleSide}));m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
}
function clip(poly,xMin,xMax,yMin,yMax){for(const [axis,bound,sign]of [[0,xMin,1],[0,xMax,-1],[1,yMin,1],[1,yMax,-1]]){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ia=(a[axis]-bound)*sign>=-1e-7,ib=(b[axis]-bound)*sign>=-1e-7;if(ia)out.push(a);if(ia!==ib){const t=(bound-a[axis])/(b[axis]-a[axis]);out.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}}poly=out;if(!poly.length)break;}return poly;}
export function tiledSurface(parent,vertices,seed=1,tint=0xb86f55){const origin=vertices[0],u=vertices[1].clone().sub(origin).normalize(),normal=vertices[1].clone().sub(origin).cross(vertices[2].clone().sub(origin)).normalize();if(normal.y<0)normal.negate();const v=normal.clone().cross(u).normalize();let polygon=vertices.map(p=>{const d=p.clone().sub(origin);return [d.dot(u),d.dot(v)];});const minU=Math.min(...polygon.map(p=>p[0])),maxU=Math.max(...polygon.map(p=>p[0])),minV=Math.min(...polygon.map(p=>p[1])),maxV=Math.max(...polygon.map(p=>p[1]));const batch=new Batch(),tw=.29,th=.43;
 for(let r=Math.floor(minV/th);r<=Math.ceil(maxV/th);r++)for(let col=Math.floor(minU/tw);col<=Math.ceil(maxU/tw);col++){const shade=.78+.35*noise(col+seed,r),base=new T.Color(tint).multiplyScalar(shade);for(let strip=0;strip<3;strip++){const x0=col*tw+strip*tw/3+.003,x1=col*tw+(strip+1)*tw/3-.003,y0=r*th+.013,y1=(r+1)*th-.011;const poly=clip(polygon,x0,x1,y0,y1);if(poly.length<3)continue;const pts=poly.map(([x,y])=>origin.clone().addScaledVector(u,x).addScaledVector(v,y).addScaledVector(normal,.024+.027*Math.sin((x/tw-col)*Math.PI)+.013*(1-(y-r*th)/th)));const tone=base.clone().multiplyScalar(strip===0?.86:strip===1?1.05:.95);for(let j=1;j<pts.length-1;j++)batch.tri(pts[0],pts[j],pts[j+1],tone);}}
 return batch.mesh(parent);}
export function roofCaps(model,a,b,r=.1){const length=a.distanceTo(b),axis=b.clone().sub(a).normalize();let up=V(0,1,0),side=axis.clone().cross(up).normalize();up=side.clone().cross(axis).normalize();const batch=new Batch();for(let t=0;t<length;t+=.34){const end=Math.min(length,t+.32),color=new T.Color(0xc8876d).multiplyScalar(.88+.2*noise(t*23));for(let j=0;j<6;j++){const f=j/6*Math.PI,g=(j+1)/6*Math.PI;const p=(d,ang)=>a.clone().addScaledVector(axis,d).addScaledVector(side,Math.cos(ang)*r).addScaledVector(up,Math.sin(ang)*r+.025);batch.quad(p(t,f),p(end,f),p(end,g),p(t,g),color);}}return batch.mesh(model.root);}
function pavers(model,x0,x1,z0,z1,y,step=.35,color=0xa78472){const b=new Batch();for(let r=0,z=z0;z<z1;z+=step,r++)for(let x=x0-step*(r%2)/2;x<x1;x+=step){const l=Math.max(x+.012,x0),rr=Math.min(x+step-.012,x1),f=z+.012,back=Math.min(z+step-.012,z1),c=new T.Color(color).multiplyScalar(.85+.25*noise(x*13,r));if(rr>l)b.quad(V(l,y,f),V(l,y,back),V(rr,y,back),V(rr,y,f),c);}b.mesh(model.root);}
function foliage(model,x,z,h,r,label){const trunk=model.box(.22,h*.66,.22,x,h*.33,z,M.wood,model.root,true,label);const batch=new Batch();for(let i=0;i<24;i++){const a=i*2.39996,rr=r*Math.sqrt((i+.5)/24),yy=h-r*.65+Math.cos(i*1.61)*r*.55,center=V(x+Math.cos(a)*rr*.67,yy,z+Math.sin(a)*rr*.67),geo=new T.SphereGeometry(r*(.45+.12*noise(i)),10,8).toNonIndexed();const p=geo.attributes.position;for(let k=0;k<p.count;k+=3){const c=new T.Color(0x3b642c).multiplyScalar(.72+noise(i*3,k)*.55);batch.tri(V().fromBufferAttribute(p,k).add(center),V().fromBufferAttribute(p,k+1).add(center),V().fromBufferAttribute(p,k+2).add(center),c);}geo.dispose();}const crown=batch.mesh(model.root);crown.userData.label=label;model.obstacles.push(crown);}
function palm(model,x,z,h){const start=V(x,0,z),tip=V(x-.5,h,z-.2);model.beam(start,tip,.14,M.wood);for(let j=0;j<20;j++){const p=start.clone().lerp(tip,j/20);const ring=new T.Mesh(new T.TorusGeometry(.145,.012,3,8),M.shadow);ring.rotation.x=Math.PI/2;ring.position.copy(p);model.root.add(ring);}const batch=new Batch();for(let k=0;k<13;k++){const angle=k*2.399,span=3.2+noise(k)*.8;const center=t=>tip.clone().add(V(Math.cos(angle)*t*span,1.15*Math.sin(t*Math.PI)-1.35*t,Math.sin(angle)*t*span));const perpendicular=V(-Math.sin(angle),0,Math.cos(angle));model.beam(center(0),center(.55),.027,M.grass);for(let i=1;i<17;i++){const t=i/18,p=center(t),width=.72*Math.sin(Math.PI*t);for(const s of [-1,1]){const end=center(Math.min(1,t+.17)).addScaledVector(perpendicular,width*s).add(V(0,-.12,0)),side=perpendicular.clone().multiplyScalar(.08);const c=new T.Color(0x355a34).multiplyScalar(.8+noise(k,i)*.5);batch.tri(p.clone().add(side),end,p.clone().sub(side),c);}}}const leaves=batch.mesh(model.root);leaves.userData.label='Garden palm';model.obstacles.push(leaves);}

export function buildArchitecture(model){const c=model.config,W=c.width,D=c.depth,E=c.eaves,front=D/2-2.5,upper=E*.5,terraceFront=front+4.65,left=-W/2,right=W/2,bayX=W*.27,bayW=W*.43,bayFront=front+1.8;const box=(...a)=>model.box(...a),beam=(...a)=>model.beam(...a);
 model.root.rotation.y=(180-c.bearing)*Math.PI/180;
 // The plot is a corner lot: long side lawn, a broad front driveway and a narrow left service passage.
 box(40,.7,42,0,-.46,1,M.earth);box(40,.12,42,0,-.12,1,M.grass);box(5,.12,42,14.6,-.07,1,M.asphalt);box(40,.12,4.4,0,-.07,20,M.asphalt);
 box(24,.14,.45,0,.03,17.65,M.stone);box(.45,.16,33,11.9,.04,1,M.stone);box(1.05,.06,32,-8.4,.08,1,M.shadow);
 // Recessed main volume and projecting right-hand bay. Upper windows are not repeated across the façade.
 box(W,.32,D-2.1,0,.18,-1.05,M.stone);box(W,E-.3,D-2.5,0,E/2,-1.25,M.plaster,model.root,true,'Main bungalow');
 box(bayW,E-.25,2.05,bayX,E/2,front+.93,M.plaster,model.root,true,'Projecting front bay');
 for(const y of [.35,upper-.12,E-.13]){box(W+.08,.16,D-2.4,0,y,-1.2,M.white);box(bayW+.12,.16,2.2,bayX,y,front+1,M.white);}
 // Deep masonry terrace slab, perforated balustrades, square porch columns and capitals.
 const tx=(left+.5)/2,tw=.5-left,tz=(front+terraceFront)/2;
 box(tw+.25,.27,terraceFront-front,tx,upper,tz,M.white,model.root,true,'Car porch and upper terrace');
 box(tw,.08,terraceFront-front-.2,tx,upper+.17,tz-.08,M.shadow);pavers(model,left+.08,.55,front+.05,terraceFront-.1,upper+.22,.58,0xd1d0c7);
 for(const x of [left+.22,.48]){box(.34,upper-.12,.38,x,upper/2,terraceFront-.26,M.white);box(.52,.18,.56,x,.22,terraceFront-.26,M.stone);box(.49,.18,.54,x,upper-.28,terraceFront-.26,M.white);}
 const railing=(x1,z1,x2,z2,base,h=1.03)=>{const a=V(x1,0,z1),b=V(x2,0,z2),length=a.distanceTo(b),count=Math.max(2,Math.round(length/.43)),along=b.clone().sub(a).normalize(),horizontal=Math.abs(x2-x1)>Math.abs(z2-z1);const slab=(length,hh,dd,p,y)=>box(horizontal?length:dd,hh,horizontal?dd:length,p.x,y,p.z,M.white);const mid=a.clone().add(b).multiplyScalar(.5);slab(length,.42,.2,mid,base+.21);slab(length+.08,.12,.26,mid,base+h-.06);for(let i=0;i<=count;i++){const p=a.clone().addScaledVector(along,length*i/count);slab(.24,h-.44,.2,p,base+.42+(h-.44)/2);}slab(length,.06,.25,mid,base+.43);};
 railing(left+.04,terraceFront-.06,.6,terraceFront-.06,upper+.13);railing(left+.04,front+.2,left+.04,terraceFront,upper+.13);
 // Front bay has its own masonry balcony and recessed dark window band on both levels.
 for(const base of [.31,upper+.12]){box(bayW+.15,.2,1.1,bayX,base,bayFront+.35,M.white);railing(bayX-bayW/2+.08,bayFront+.83,bayX+bayW/2-.08,bayFront+.83,base+.1,.92);}
 const window=(x,y,z,w,h,side=0)=>{const group=new T.Group();group.position.set(x,y,z);group.rotation.y=side;model.root.add(group);box(w+.2,h+.22,.18,0,0,0,M.white,group);box(w,h,.2,0,0,.05,M.dark,group);box(w-.13,h-.13,.04,0,0,.162,M.glass,group);const divisions=Math.max(2,Math.round(w/.72));for(let i=1;i<divisions;i++)box(.045,h,.055,-w/2+i*w/divisions,0,.2,M.frame,group);box(w,.045,.06,0,h*.2,.205,M.frame,group);box(w+.3,.10,.32,0,-h/2-.07,.03,M.stone,group);for(const s of [-1,1])box(.12,h-.17,.015,s*(w/2-.12),0,.19,M.curtain,group);};
 window(left+1.6,upper+1.57,front+.1,2.5,1.8);window(-.14,upper+1.55,front+.1,.64,2.05);
 box(.92,2.6,.17,-1.45,upper+1.32,front+.1,M.white);box(.75,2.45,.19,-1.45,upper+1.29,front+.13,M.door);for(const y of [upper+.75,upper+1.75])box(.54,.7,.03,-1.45,y,front+.24,M.wood);box(.035,.16,.04,-1.16,upper+1.28,front+.28,M.metal);
 window(bayX,upper+1.76,bayFront+.06,bayW-.9,1.78);window(bayX,2.22,bayFront+.06,bayW-.9,1.74);
 for(const x of [bayX-bayW/2+.1,bayX+bayW/2-.1])box(.26,E,.27,x,E/2,bayFront+.15,M.white);
 window(-2.8,1.7,front+.1,2.8,2.6);box(3.4,.12,.48,-2.8,.24,front+.39,M.stone);box(3.2,.12,.35,-2.8,.35,front+.26,M.white);
 for(const side of [-1,1])for(const z of [-D/2+2.1,-D/2+5.6,front-1.5])for(const y of [1.85,upper+1.63])window(side*(W/2+.025),y,z,1.48,1.65,side*Math.PI/2);
 // Roof silhouette: the main hip, a crossing rear hip, a large right gable and its shallow tiled apron.
 const spec=model.roofSpec();model.makeHipRoof(0,spec.z,spec.w,spec.d,E,c.pitch*Math.PI/180,M.roof,'Main roof',true);
 model.makeHipRoof(0,-D/2+2.4,W*.78,5.9,E+.13,27*Math.PI/180,M.roof,'Rear crossing roof',false,true);
 const gw=bayW+.7,gz=bayFront-.13,gd=3.4,gy=E+.02,rise=gw/2*Math.tan(c.pitch*Math.PI/180);
 model.makeGable(bayX,gz,gw,gd,gy,rise,M.roof,'Front gable');
 const apronZ=gz+gd/2,apron=[V(bayX-gw/2,gy,apronZ-.03),V(bayX+gw/2,gy,apronZ-.03),V(bayX+gw/2,gy-.48,apronZ+.86),V(bayX-gw/2,gy-.48,apronZ+.86)];const apronGeo=new T.BufferGeometry();apronGeo.setAttribute('position',new T.Float32BufferAttribute([0,1,2,0,2,3].flatMap(i=>apron[i].toArray()),3));apronGeo.computeVertexNormals();const apronBase=new T.Mesh(apronGeo,M.roof);apronBase.castShadow=apronBase.receiveShadow=true;apronBase.userData.label='Front gable apron';model.root.add(apronBase);model.obstacles.push(apronBase);tiledSurface(model.root,apron,41);box(gw,.17,.15,bayX,gy-.53,apronZ+.87,M.white);
 // Eave fascia and gutters, with downpipes at wall corners.
 for(const side of [-1,1]){box(.12,.19,spec.d,side*spec.w/2,E-.09,spec.z,M.white);box(.13,.09,spec.d,side*(spec.w/2+.07),E-.02,spec.z,M.gutter);}
 for(const z of [spec.z-spec.d/2,spec.z+spec.d/2]){box(spec.w,.19,.12,0,E-.09,z,M.white);box(spec.w,.09,.13,0,E-.01,z+.05,M.gutter);}
 for(const x of [left+.08,right-.08])for(const z of [-D/2+.1,front-.05]){box(.08,E-.35,.08,x,E/2,z,M.gutter);for(const yy of [1.4,3.1,4.8,6.5])if(yy<E)box(.11,.035,.11,x,yy,z,M.frame);}
 // Solar water heater visible on the upper left roof, separate from the proposed PV array.
 const hx=-W*.3,hz=-D*.23,hy=E+Math.tan(c.pitch*Math.PI/180)*(spec.w/2-Math.abs(hx));
 const heater=new T.Group();heater.position.set(hx,hy+.15,hz);heater.rotation.z=c.pitch*Math.PI/180;model.root.add(heater);box(1.38,.09,2.1,0,0,0,M.frame,heater);box(1.24,.035,1.93,0,.065,0,M.glass,heater);for(let j=0;j<7;j++)box(.025,.02,1.9,-.54+j*.18,.087,0,M.metal,heater);const tank=new T.Mesh(new T.CylinderGeometry(.23,.23,1.6,14),M.white);tank.rotation.x=Math.PI/2;tank.position.set(.63,.31,0);heater.add(tank);tank.castShadow=true;heater.traverse(o=>{if(o.isMesh){o.userData.label='Existing solar water heater';model.obstacles.push(o);}});
 // Terracotta drive, gate pillars, arched paired metal gates and boundary coping.
 const driveLeft=left-.4,driveRight=.65;box(driveRight-driveLeft,.04,17.3-front,(driveRight+driveLeft)/2,.05,(17.3+front)/2,M.paver);pavers(model,driveLeft,driveRight,front,17.4,.083,.36);
 const fenceLeft=left-2.05,fenceRight=11.65;for(const x of [fenceLeft,fenceRight]){box(.2,1.4,32.4,x,.7,1.3,M.plaster);box(.3,.1,32.4,x,1.45,1.3,M.white);for(let z=-14.6;z<=17.4;z+=4) {box(.42,1.85,.45,x,.925,z,M.white);box(.54,.1,.56,x,1.91,z,M.stone);}}
 const gateZ=17.5;for(const [x,w]of [[(fenceLeft+driveLeft)/2,driveLeft-fenceLeft],[(driveRight+fenceRight)/2,fenceRight-driveRight]]){box(w,1.1,.24,x,.55,gateZ,M.plaster);box(w+.1,.12,.35,x,1.16,gateZ,M.white);}
 for(const x of [driveLeft-.16,driveRight+.16]){box(.55,2,.6,x,1,gateZ,M.white);box(.71,.13,.75,x,2.07,gateZ,M.white);box(.32,.7,.04,x,.55,gateZ+.32,M.shadow);box(.16,.24,.06,x,1.7,gateZ+.34,M.dark);}
 const gateWidth=driveRight-driveLeft-.23;for(const side of [-1,1]){const center=(driveLeft+driveRight)/2+side*gateWidth/4,half=gateWidth/2;for(let i=0;i<=15;i++){const x=center-half/2+i*half/15,h=1.32+.26*(1-Math.abs((x-(driveLeft+driveRight)/2)/(gateWidth/2)));box(.035,h,.055,x,h/2+.1,gateZ,M.metal);}for(const y of [.22,.62,1.12])box(half,.045,.075,center,y,gateZ,M.metal);const a=V(center-half/2,1.42+.26*(1-Math.abs((center-half/2-(driveLeft+driveRight)/2)/(gateWidth/2))),gateZ),b=V(center+half/2,1.42+.26*(1-Math.abs((center+half/2-(driveLeft+driveRight)/2)/(gateWidth/2))),gateZ);beam(a,b,.035,M.metal);}
 // Narrow drainage and the ascending passage along the left boundary.
 box(.32,.04,31,fenceLeft+.4,.02,1,M.dark);for(let j=0;j<24;j++){const z=16.6-j*.47;box(.82,.07+.065*j,.46,fenceLeft-.7,(.07+.065*j)/2,z,M.stone);}
 box(.8,.06,17,fenceLeft-.7,1.58,-5,M.stone);
 // Neighbour context keeps domestic proportions and subdued materials.
 for(const side of [-1,1]){const nx=side*(W/2+c.neighbourDistance+4.2),nz=-2,nh=c.neighbourHeight,nw=8.4;box(nw,nh,11.6,nx,nh/2,nz,M.plaster,model.root,true,side<0?'Left neighbouring house':'Right neighbouring house');model.makeHipRoof(nx,nz,nw+.65,12.3,nh,27*Math.PI/180,material(0x9d7969,{side:T.DoubleSide}),side<0?'Left neighbouring roof':'Right neighbouring roof',false);for(const y of [1.6,nh*.76])for(const x of [-2.8,0,2.8])window(nx+x,y,nz+5.85,1.2,1.6);box(nw+.15,.18,11.7,nx,nh*.5,nz,M.white);}
 foliage(model,c.treeX,D/2+c.treeDistance,c.treeHeight,1.9,'Front garden tree');foliage(model,9.15,15.1,c.treeHeight*.98,1.85,'Front boundary tree');foliage(model,8.8,-10,6.7,1.55,'Rear garden tree');foliage(model,-7,-11.5,6.5,1.4,'Rear boundary tree');palm(model,9.3,11.9,7.5);
 for(let z=-12;z<13;z+=1.45)foliage(model,fenceLeft+.75,z,1.1,.4,'Boundary hedge');
 // Subtle lawn variation uses planar patches, not a flat, uniformly coloured block.
 const lawn=new Batch();for(let i=0;i<480;i++){const x=-7.5+noise(i)*18.8,z=-14+noise(i,5)*31;if((x>left-.6&&x<right+.3&&z<terraceFront+.2)||(x>driveLeft-.15&&x<driveRight+.15&&z>front))continue;const size=.1+noise(i,2)*.35,col=new T.Color(0x6e874d).multiplyScalar(.8+.4*noise(i,9));lawn.tri(V(x,.085,z),V(x+size,.085,z+.06),V(x+.09,.085,z+size),col);}lawn.mesh(model.root);
 model.obstacles.forEach(o=>o.userData.solarOccluder=true);model.root.add(model.panels,model.overlay);model.makeFaces();model.root.updateMatrixWorld(true);
}
