import * as T from 'three';
import {shadowMap} from './software-shadow.js';
// Software depth buffer for devices without WebGL. Geometry, picking and
// calculations are shared with the accelerated Three.js view.
export class CompatibilityRenderer {
 constructor(){this.domElement=document.createElement('canvas');this.ctx=this.domElement.getContext('2d');this.shadowMap={};this.w=1;this.h=1;this.last='';this.lastAt=0;this.compatibility=true;this.sunDirection=new T.Vector3(1,1,1).normalize();}
 setPixelRatio(){}
 setSize(w,h){this.w=Math.round(w);this.h=Math.round(h);this.domElement.width=this.w;this.domElement.height=this.h;this.domElement.style.width=w+'px';this.domElement.style.height=h+'px';this.buffer=this.ctx.createImageData(this.w,this.h);this.depth=new Float32Array(this.w*this.h);this.last='';}
 invalidate(){this.last='';}
 render(scene,camera){const now=performance.now();if(now-this.lastAt<75)return;const signature=[...camera.position.toArray(),...camera.quaternion.toArray(),...this.sunDirection.toArray()].map(n=>n.toFixed(3)).join(',');if(this.last===signature)return;this.last=signature;this.lastAt=now;scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const shadowKey=scene.children.map(o=>o.uuid).join(',')+this.sunDirection.toArray().map(v=>v.toFixed(3)).join(',');if(this.shadowKey!==shadowKey){this.shadowKey=shadowKey;this.shadow=this.sunDirection.y>0?shadowMap(scene,this.sunDirection):null;}const shadow=this.shadow;const matrix=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),w=this.w,h=this.h,depth=this.depth,pixels=this.buffer.data,light=this.sunDirection,cam=camera.position;depth.fill(Infinity);for(let i=0;i<pixels.length;i+=4){pixels[i]=197;pixels[i+1]=210;pixels[i+2]=209;pixels[i+3]=255;}
 const blend=(i,z,col,alpha,shade=1)=>{if(z>depth[i]+.000008||z>1||z< -1)return;depth[i]=z;const q=i*4;pixels[q]=col[0]*shade*alpha+pixels[q]*(1-alpha);pixels[q+1]=col[1]*shade*alpha+pixels[q+1]*(1-alpha);pixels[q+2]=col[2]*shade*alpha+pixels[q+2]*(1-alpha);};
 const drawTriangle=(a,b,c,col,alpha,receiveShadow,objectId)=>{const minX=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),maxX=Math.min(w-1,Math.ceil(Math.max(a.x,b.x,c.x))),minY=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),maxY=Math.min(h-1,Math.ceil(Math.max(a.y,b.y,c.y)));const den=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(den)<.00001)return;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((b.y-c.y)*(x+.5-c.x)+(c.x-b.x)*(y+.5-c.y))/den,v=((c.y-a.y)*(x+.5-c.x)+(a.x-c.x)*(y+.5-c.y))/den,t=1-u-v;if(u>=0&&v>=0&&t>=0){let shade=1;if(receiveShadow&&shadow&&a.shadow&&b.shadow&&c.shadow){const weight=u*a.iw+v*b.iw+t*c.iw,pu=u*a.iw/weight,pv=v*b.iw/weight,pt=t*c.iw/weight;const sx=Math.round(pu*a.shadow.x+pv*b.shadow.x+pt*c.shadow.x),sy=Math.round(pu*a.shadow.y+pv*b.shadow.y+pt*c.shadow.y),sz=pu*a.shadow.z+pv*b.shadow.z+pt*c.shadow.z;if(sx>=0&&sy>=0&&sx<shadow.size&&sy<shadow.size&&shadow.owners[sy*shadow.size+sx]!==objectId&&shadow.depth[sy*shadow.size+sx]>sz+.26)shade=.64;}blend(y*w+x,u*a.z+v*b.z+t*c.z,col,alpha,shade);}}};
 const lines=[];scene.traverse(obj=>{if(!obj.visible||!obj.geometry)return;let parent=obj.parent;while(parent){if(!parent.visible)return;parent=parent.parent;}const geo=obj.geometry,pos=geo.attributes.position,mat=Array.isArray(obj.material)?obj.material[0]:obj.material;if(!pos||!mat||mat.visible===false)return;const projected=[],worlds=[];for(let i=0;i<pos.count;i++){const world=new T.Vector3().fromBufferAttribute(pos,i).applyMatrix4(obj.matrixWorld);worlds.push(world);const p=world.clone().applyMatrix4(matrix);projected.push({x:(p.x*.5+.5)*w,y:(-.5*p.y+.5)*h,z:p.z,iw:1/(matrix.elements[3]*world.x+matrix.elements[7]*world.y+matrix.elements[11]*world.z+matrix.elements[15]),shadow:shadow?shadow.project(world):null});}const ids=geo.index?.array;
 if(obj.isMesh){const length=ids?ids.length:pos.count;for(let i=0;i<length;i+=3){const ia=ids?ids[i]:i,ib=ids?ids[i+1]:i+1,ic=ids?ids[i+2]:i+2,a=projected[ia],b=projected[ib],c=projected[ic];if(!a||!b||!c||a.z>1||b.z>1||c.z>1||a.z< -1||b.z< -1||c.z< -1)continue;const normal=new T.Vector3().subVectors(worlds[ib],worlds[ia]).cross(new T.Vector3().subVectors(worlds[ic],worlds[ia])).normalize();const facing=normal.dot(new T.Vector3().subVectors(cam,worlds[ia]));if(mat.side!==T.DoubleSide&&facing<=0)continue;if(facing<0)normal.negate();const col=mat.color?.clone()||new T.Color(0x999999);if(mat.vertexColors&&geo.attributes.color){const colors=geo.attributes.color;col.multiply(new T.Color(colors.getX(ia),colors.getY(ia),colors.getZ(ia)));}if(!mat.isMeshBasicMaterial){col.multiplyScalar(.6+.4*Math.max(0,normal.dot(light)));if(mat.emissive)col.add(mat.emissive.clone().multiplyScalar(.25));}const hex=col.getHex();drawTriangle(a,b,c,[hex>>16&255,hex>>8&255,hex&255],mat.opacity??1,obj.receiveShadow&&!mat.isMeshBasicMaterial,obj.id);}}
 else if(obj.isLine){const stride=obj.isLineSegments?2:1,hex=mat.color?.getHex()||0x607b85;for(let i=0;i<projected.length-1;i+=stride)lines.push({a:projected[i],b:projected[i+1],col:[hex>>16&255,hex>>8&255,hex&255],alpha:mat.opacity??1,dash:!!mat.isLineDashedMaterial});}});
 for(const {a,b,col,alpha,dash}of lines){if(a.z>1||b.z>1||a.z< -1||b.z< -1)continue;const steps=Math.ceil(Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y)));if(steps>w+h)continue;for(let i=0;i<=steps;i++){if(dash&&i%10>5)continue;const t=i/Math.max(1,steps),x=Math.round(a.x+(b.x-a.x)*t),y=Math.round(a.y+(b.y-a.y)*t);if(x>=0&&x<w&&y>=0&&y<h)blend(y*w+x,a.z+(b.z-a.z)*t-.00001,col,alpha);}}this.ctx.putImageData(this.buffer,0,0);}
}
