import * as T from 'three';
import {CompatibilityRenderer} from './compatibility.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {BungalowModel,defaults,rad} from './model.js';
import {estimate,dailyCurve,sunPosition,shadeAt,irradiance} from './solar.js';

const $=id=>document.getElementById(id),all=q=>[...document.querySelectorAll(q)];
let config={...defaults},date='2026-09-21',hour=10.5,layout='B',layer='realistic',editing=false,tool='move',selected=null,playing=false,history=[],layouts,curves={},current,model,drag=null,clickStart=null,revision=0,recalcTimer,toastTimer,quoteValues={A:'',B:'',C:''};
const labels={A:'Initial layout',B:'Repositioned layout',C:'Expanded layout'};
const descriptions={A:'A starting arrangement across the front and side.',B:'Same panel count. A different use of the roof.',C:'Explore what additional panels contribute.'};
const scene=new T.Scene();scene.background=new T.Color(0xc5d2d1);scene.fog=new T.Fog(0xc5d2d1,80,165);
const camera=new T.PerspectiveCamera(36,1,.1,250);let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});}catch{renderer=new CompatibilityRenderer();}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=T.SRGBColorSpace;$('scene').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=14;controls.maxDistance=95;controls.maxPolarAngle=Math.PI*.48;controls.target.set(0,3,0);controls.enablePan=true;
scene.add(new T.HemisphereLight(0xe3f1f5,0x8a9175,2.2));const sunlight=new T.DirectionalLight(0xfff0d3,3.4);sunlight.castShadow=true;sunlight.shadow.mapSize.set(2048,2048);sunlight.shadow.camera.left=-36;sunlight.shadow.camera.right=36;sunlight.shadow.camera.top=36;sunlight.shadow.camera.bottom=-36;sunlight.shadow.camera.near=1;sunlight.shadow.camera.far=130;sunlight.shadow.bias=-.00018;sunlight.shadow.normalBias=.025;scene.add(sunlight,sunlight.target);
const ground=new T.Mesh(new T.PlaneGeometry(300,300),new T.MeshStandardMaterial({color:0xb8c9c7,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.8;ground.receiveShadow=true;scene.add(ground);
let sunPath=new T.Group();scene.add(sunPath);const sunOrb=new T.Mesh(new T.SphereGeometry(.6,20,16),new T.MeshBasicMaterial({color:0xffdb92}));scene.add(sunOrb);
let selectionOutline=null,cameraTween=null,lastFrame=performance.now(),lastSim=0,loopCount=0;
const formatTime=h=>{const m=Math.round(h*60),hh=Math.floor(m/60)%24;return String(hh).padStart(2,'0')+':'+String(m%60).padStart(2,'0');};
const direction=b=>['N','NE','E','SE','S','SW','W','NW'][Math.round(((b%360)+360)%360/45)%8];
const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3400);}
function snapshot(){history.push({layouts:structuredClone(layouts),config:{...config},layout});if(history.length>30)history.shift();}
function currentPanels(){return layouts[layout];}
function validPanels(list){return list.filter(p=>!p.invalid);}
function flagPanels(){for(const k of ['A','B','C'])for(const p of layouts[k])p.invalid=!model.valid(p,layouts[k]);}
function buildSite(preserve=false){if(model)model.destroy();model=new BungalowModel(scene,config);if(!preserve)layouts=model.layouts();else flagPanels();model.setPanels(currentPanels());$('bearing-display').textContent='↙ '+Math.round(config.bearing)+'° '+direction(config.bearing)+' facing';all('#settings-form input').forEach(el=>{if(el.name in config)el.value=config[el.name];});drawSunPath();recalculate();}
function drawSunPath(){while(sunPath.children.length){const o=sunPath.children.pop();o.geometry?.dispose();o.material?.dispose();}const pts=[];for(let h=0;h<=24;h+=.125){const s=sunPosition(date,h,config);if(s.elevation>0)pts.push(s.direction.clone().multiplyScalar(25).add(new T.Vector3(0,.2,0)));}if(pts.length>1){const line=new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineDashedMaterial({color:0xaa874b,transparent:true,opacity:.47,dashSize:.6,gapSize:.35}));line.computeLineDistances();sunPath.add(line);}}
function recalculate(){const rev=++revision;$('calc-status').textContent='CALCULATING…';clearTimeout(recalcTimer);updateInstant();recalcTimer=setTimeout(()=>{if(rev!==revision)return;curves={};for(const k of ['A','B','C'])curves[k]=dailyCurve(model,layouts[k],date,config);buildSunlightOverlay();updateInstant();updateDaily();drawChart();$('calc-status').textContent='SCENARIO READY';$('loading').hidden=true;},20);}
function updateDaily(){const c=curves[layout];if(!c)return;$('daily-energy').innerHTML=fmt(c.energy)+' <small>kWh</small>';const daylight=c.data.filter(r=>r.elevation>0);$('sunset-info').textContent=daylight.length?'Daylight ≈ '+formatTime(daylight[0].hour)+'–'+formatTime(daylight.at(-1).hour):'No daylight in this scenario';if($('compare-dialog').open)renderComparison();if($('summary-dialog').open)renderProposal();}
function updateInstant(){current=estimate(model,currentPanels(),date,hour,config);const count=validPanels(currentPanels()).length,size=count*config.panelWatts/1000;const time=formatTime(hour);$('scene-time').textContent=time;$('time-value').textContent=time;$('time-slider').value=hour;$('current-time-small').textContent=time+' local';$('sun-elevation').textContent=current.sun.elevation>0?'SUN ELEVATION '+Math.round(current.sun.elevation)+'°':'SUN BELOW HORIZON';$('power-now').textContent=fmt(current.power,2);$('panel-count').textContent=count;$('system-size').innerHTML=fmt(size,2)+' <small>kWp</small>';$('shaded-count').innerHTML=current.shaded+' <small>/ '+count+'</small>';$('shading-impact').innerHTML=current.baseline>.005?fmt(current.loss,1)+'<small>%</small>':'—';const relative=current.baseline>.005?100-current.loss:0;$('power-relative').textContent=current.baseline>.005?fmt(relative,0)+'% of unshaded output':'No solar production';$('power-meter').style.width=Math.max(0,Math.min(100,size?current.power/size*100:0))+'%';
 if(renderer.compatibility)renderer.sunDirection.copy(current.sun.direction);const target=new T.Vector3(0,3,0);sunlight.position.copy(current.sun.direction).multiplyScalar(65).add(target);sunlight.target.position.copy(target);sunlight.intensity=current.sun.elevation>0?Math.max(.2,3.4*Math.pow(Math.sin(rad(current.sun.elevation)),.3)):0;sunOrb.position.copy(current.sun.direction).multiplyScalar(25).add(new T.Vector3(0,.2,0));sunOrb.visible=current.sun.elevation>0;
 const invalid=currentPanels().filter(p=>p.invalid).length;const worst=Object.entries(current.per).sort((a,b)=>b[1].shade-a[1].shade)[0];
 if(invalid){$('insight-title').textContent=invalid+' panel'+(invalid>1?'s need':' needs')+' repositioning';$('insight-text').textContent='Red panels no longer fit the modelled roof. They are excluded from output. Enter Edit design to move or remove them.';}
 else if(current.sun.elevation<=0){$('insight-title').textContent='The sun is below the horizon';$('insight-text').textContent='Move the time slider into daylight to inspect sunlight and shading on your roof.';}
 else if(current.shaded&&worst){$('insight-title').textContent='Shade has a source';$('insight-text').textContent=worst[1].source+' blocks direct sunlight at '+worst[0]+'. Estimated system output is '+fmt(current.loss)+'% below the unshaded case.';}
 else{$('insight-title').textContent='A clear view of the sun';$('insight-text').textContent='No modelled obstruction shades sun-facing panels at this time. Roof direction and sun angle still affect output.';}
 $('inspect-shade').hidden=!current.shaded;updatePanelColours();updatePanelDetails();drawChart();}
function updatePanelColours(){renderer.invalidate?.();const curve=curves[layout];for(const g of model.panelObjects){const id=g.userData.panelId,p=currentPanels().find(p=>p.id===id),v=current.per[id],material=g.userData.surface.material;if(p.invalid)material.color.set(0xa44939);else if(layer==='shade'){const ratio=v&&v.base>1?v.dc/v.base:0;material.color.copy(new T.Color(0x465a80).lerp(new T.Color(0xf0c16e),ratio));}else if(layer==='daily'){const hours=curve?.panelSun[id]||0;material.color.copy(new T.Color(0x455d85).lerp(new T.Color(0xf2c976),Math.min(1,hours/11)));}else material.color.set(0x163d53);material.emissive.set(id===selected?0x3d3820:0x000000);g.userData.frame.material.color.set(id===selected?0xffce77:p.invalid?0xe9765c:0x91a5af);}}
function buildSunlightOverlay(){model.disposeGroup(model.overlay);for(const [face,f]of Object.entries(model.faces)){for(let u=-f.length/2+.7;u<f.length/2;u+=.72)for(let v=.7;v<5.5;v+=.72){const p={face,u,v};const point=model.point(p);if(!model.surfaceFits(p,0,0,.3))continue;let hours=0;for(let h=6;h<=20;h+=.5){const sun=sunPosition(date,h,config),n=model.worldNormal(p);if(sun.elevation>0&&n.dot(sun.direction)>0){const sh=shadeAt(model,p,sun,1);hours+=(1-sh.fraction)*.5;}}const col=new T.Color(0x425f83).lerp(new T.Color(0xeec46e),Math.min(hours/11,1));const mesh=new T.Mesh(new T.PlaneGeometry(.71,.71),new T.MeshBasicMaterial({color:col,transparent:true,opacity:.78,depthWrite:false,side:T.DoubleSide}));mesh.position.copy(point).addScaledVector(f.n,-.085);mesh.quaternion.copy(f.q);model.overlay.add(mesh);}}model.overlay.visible=layer==='daily';}
function selectPanel(id){selected=id;const p=currentPanels().find(p=>p.id===id);if(id&&!p)selected=null;$('system-details').hidden=!!selected;$('panel-details').hidden=!selected;updatePanelColours();updatePanelDetails();}
function updatePanelDetails(){if(!selected){$('panel-label').hidden=true;return;}const p=currentPanels().find(p=>p.id===selected);if(!p)return;const v=current?.per[selected];$('selected-id').textContent=selected+' · '+p.face.charAt(0).toUpperCase()+p.face.slice(1)+' roof';$('selected-power').textContent=v?fmt(v.dc,0):'—';const n=model.worldNormal(p),bearing=(Math.atan2(n.x,-n.z)*180/Math.PI+360)%360;const rows=[['Rated capacity',config.panelWatts+' W'],['Surface shaded',v?fmt(v.shade*100,0)+'%':'Invalid placement'],['Sunlight received',v?fmt(v.irradiance,0)+' W/m²':'—'],['Shade source',v?.source||'None at this time'],['Roof direction',Math.round(bearing)+'° '+direction(bearing)],['Roof tilt',config.pitch+'°'],['Direct sun today',curves[layout]?fmt(curves[layout].panelSun[selected]||0)+' h':'Calculating…']];$('panel-data').innerHTML=rows.map(([k,val])=>'<dt>'+k+'</dt><dd>'+val+'</dd>').join('');$('panel-label').hidden=false;$('panel-label').textContent=selected+' · '+(v?fmt(v.dc,0)+' W':'Reposition');}
function setLayout(key){if(!['A','B','C'].includes(key))throw Error('Unknown layout');layout=key;selected=null;model.setPanels(currentPanels());all('[data-layout]').forEach(b=>b.classList.toggle('active',b.dataset.layout===key));$('layout-title').textContent=labels[key];$('layout-desc').textContent=descriptions[key];document.querySelector('.small-index').textContent='0'+(['A','B','C'].indexOf(key)+1)+' / 03';selectPanel(null);updateInstant();updateDaily();}
function setLayer(value){layer=value;model.overlay.visible=layer==='daily';all('[data-layer]').forEach(b=>b.classList.toggle('active',b.dataset.layer===value));$('scene-legend').innerHTML=value==='realistic'?'<span class="legend-dot"></span> Click a panel to inspect':value==='shade'?'<span class="gradient-legend"></span> Low → high output relative to unshaded':'<span class="gradient-legend"></span> 0 → 11+ direct-sun hours';updatePanelColours();}
function moveCamera(pos,target,duration=650){cameraTween={start:performance.now(),duration,from:camera.position.clone(),to:pos,fromTarget:controls.target.clone(),target};}
function cameraPreset(name,immediate=false){const target=new T.Vector3(0,3.3,1.6).applyMatrix4(model.root.matrixWorld);let local=name==='detail'?new T.Vector3(5,16,29):name==='roof'?new T.Vector3(.01,47,.1):name==='street'?new T.Vector3(1,6.5,40):new T.Vector3(6,24,39);const pos=model.root.localToWorld(local);if(immediate){camera.position.copy(pos);controls.target.copy(target);controls.update();}else moveCamera(pos,target);all('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===name));}
function drawChart(){if(!curves[layout]||!current)return;const canvas=$('power-chart'),rect=canvas.getBoundingClientRect();if(!rect.width)return;const dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height,padL=24,padR=6,padT=8,padB=9;ctx.clearRect(0,0,w,h);const rows=curves[layout].data.filter(r=>r.hour>=6&&r.hour<=20);const max=Math.max(2,Math.ceil(Math.max(...rows.map(r=>r.baseline))*1.08));const xx=t=>padL+(t-6)/14*(w-padL-padR),yy=p=>h-padB-p/max*(h-padT-padB);ctx.font='9px DM Sans, sans-serif';ctx.textAlign='right';for(let i=0;i<=2;i++){const v=i*max/2;ctx.strokeStyle='#2a3b46';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(padL,yy(v));ctx.lineTo(w-padR,yy(v));ctx.stroke();ctx.fillStyle='#627f8e';ctx.fillText(v.toFixed(v%1?1:0),padL-7,yy(v)+3);}const grad=ctx.createLinearGradient(0,padT,0,h);grad.addColorStop(0,'#f4c4752d');grad.addColorStop(1,'#f4c47500');ctx.beginPath();ctx.moveTo(xx(6),yy(0));rows.forEach(r=>ctx.lineTo(xx(r.hour),yy(r.power)));ctx.lineTo(xx(20),yy(0));ctx.closePath();ctx.fillStyle=grad;ctx.fill();for(const [prop,col,dash]of [['baseline','#79909b',[4,4]],['power','#efbf76',[]]]){ctx.strokeStyle=col;ctx.lineWidth=1.7;ctx.setLineDash(dash);ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(xx(r.hour),yy(r[prop])):ctx.moveTo(xx(r.hour),yy(r[prop])));ctx.stroke();}ctx.setLineDash([]);ctx.strokeStyle='#f0c99099';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx(hour),padT);ctx.lineTo(xx(hour),h-padB);ctx.stroke();ctx.beginPath();ctx.arc(xx(hour),yy(current.power),3.8,0,Math.PI*2);ctx.fillStyle='#f7d098';ctx.fill();ctx.strokeStyle='#111d24';ctx.lineWidth=2;ctx.stroke();}
function renderComparison(){const b=curves.B,a=curves.A,c=curves.C;if(!b)return;$('comparison-content').innerHTML='<div class="comparison-grid">'+['A','B','C'].map(k=>{const n=validPanels(layouts[k]).length;return '<div class="comparison-card '+(layout===k?'selected':'')+'"><span class="letter">'+k+'</span><h3>'+labels[k]+'</h3><dl><dt>Panel count</dt><dd>'+n+'</dd><dt>Installed capacity</dt><dd>'+fmt(n*config.panelWatts/1000,2)+' <small>kWp</small></dd><dt>Energy for this day</dt><dd>'+fmt(curves[k].energy)+' <small>kWh</small></dd><dt>Daily shading impact</dt><dd>'+fmt(curves[k].loss)+' <small>%</small></dd></dl><button class="button '+(layout===k?'primary':'subtle')+'" data-choose="'+k+'">'+(layout===k?'Selected layout':'View this layout')+'</button></div>';}).join('')+'</div><div class="comparison-delta"><strong>Placement: </strong>B produces '+fmt(Math.abs(b.energy-a.energy))+' kWh '+(b.energy>=a.energy?'more':'less')+' than A on this day. '+(validPanels(layouts.A).length===validPanels(layouts.B).length?'Both use the same panel count.':'Panel counts differ after edits.')+'<br/><strong>Expansion: </strong>C adds '+(validPanels(layouts.C).length-validPanels(layouts.B).length)+' panels and '+fmt(c.energy-b.energy)+' kWh compared with B.</div>';all('[data-choose]').forEach(el=>el.onclick=()=>{setLayout(el.dataset.choose);$('compare-dialog').close();});}
function renderProposal(){const n=validPanels(currentPanels()).length,c=curves[layout];if(!c)return;renderer.render(scene,camera);const img=renderer.domElement.toDataURL('image/jpeg',.8);$('proposal-content').innerHTML='<img class="print-image" src="'+img+'" alt="Selected 3D solar proposal"/><div class="proposal-hero"><div><span>Selected arrangement</span><strong>'+labels[layout]+'</strong></div><div><span>Equipment</span><strong>'+n+' panels · '+fmt(n*config.panelWatts/1000,2)+' kWp</strong></div><div><span>Clear-sky energy · '+date+'</span><strong>'+fmt(c.energy)+' kWh</strong></div><div><span>Modelled daily shading impact</span><strong>'+fmt(c.loss)+'%</strong></div></div><div class="proposal-list">Front bearing: '+config.bearing+'° '+direction(config.bearing)+' · Roof slope: '+config.pitch+'°<br/>Location: '+config.latitude.toFixed(3)+', '+config.longitude.toFixed(3)+' · Main footprint: '+config.width+' × '+config.depth+' m<br/>Module: '+config.panelWatts+' W · Inverter: '+config.inverter+' kW AC<br/><br/><strong>Before installation:</strong> confirm dimensions, roof condition and structural capacity, access clearances, electrical design and the site survey.<br/>Photo-based concept with assumed geometry. Daily energy is an illustrative clear-sky estimate, not annual yield or bill savings.</div>';$('quote-input').value=quoteValues[layout];}
function openDialog(id){playing=false;updatePlay();$(id).showModal();}
function updatePlay(){$('play-btn').textContent=playing?'Ⅱ':'▶';$('play-btn').setAttribute('aria-label',playing?'Pause daylight animation':'Play daylight animation');}
function applyConfig(next){const keys=Object.keys(defaults);if(keys.some(k=>!Number.isFinite(next[k])))throw Error('Every assumption needs a valid number.');snapshot();config={...next};selected=null;buildSite(true);selectPanel(null);document.querySelector('.project-name small').textContent=(Math.abs(config.latitude-3.139)<.002&&Math.abs(config.longitude-101.687)<.002?'Kuala Lumpur':'Custom location')+' · Residential concept';document.querySelector('.date-controls>span').textContent='UTC'+(config.timezone>=0?'+':'')+config.timezone;toast('Assumptions updated. All layouts recalculated.');}
all('[data-layout]').forEach(el=>el.onclick=()=>setLayout(el.dataset.layout));all('[data-layer]').forEach(el=>el.onclick=()=>setLayer(el.dataset.layer));all('[data-camera]').forEach(el=>el.onclick=()=>cameraPreset(el.dataset.camera));$('reset-camera').onclick=()=>cameraPreset('overview');all('[data-direction]').forEach(el=>el.onclick=()=>{const b=+el.dataset.direction;if(b===0){moveCamera(new T.Vector3(0,48,.01),new T.Vector3(0,3,0));}else{const a=rad(b),r=48;moveCamera(new T.Vector3(Math.sin(a)*r,27,-Math.cos(a)*r),new T.Vector3(0,3,0));}all('[data-camera]').forEach(el=>el.classList.remove('active'));});
$('time-slider').oninput=e=>{hour=+e.target.value;playing=false;updatePlay();updateInstant();};$('play-btn').onclick=()=>{playing=!playing;updatePlay();};$('study-date').onchange=e=>{if(!e.target.value||!Number.isFinite(new Date(e.target.value).getTime()))return;date=e.target.value;drawSunPath();recalculate();};$('back-system').onclick=()=>selectPanel(null);
$('settings-btn').onclick=()=>openDialog('settings-dialog');$('reference-btn').onclick=()=>openDialog('photo-dialog');$('method-btn').onclick=()=>openDialog('method-dialog');$('compare-btn').onclick=()=>{renderComparison();openDialog('compare-dialog');};$('summary-btn').onclick=()=>{renderProposal();openDialog('summary-dialog');};$('quote-input').oninput=e=>quoteValues[layout]=e.target.value;$('print-btn').onclick=()=>window.print();all('.close-dialog').forEach(el=>el.onclick=()=>el.closest('dialog').close());all('dialog').forEach(el=>el.addEventListener('click',e=>{if(e.target===el){const r=el.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)el.close();}}));
$('settings-form').onsubmit=e=>{e.preventDefault();if(!$('settings-form').reportValidity())return;const next=Object.fromEntries([...new FormData(e.target).entries()].map(([k,v])=>[k,+v]));try{applyConfig(next);$('settings-dialog').close();}catch(err){toast(err.message);}};
$('reset-assumptions').onclick=()=>{applyConfig({...defaults});$('settings-dialog').close();};
$('edit-btn').onclick=()=>{editing=!editing;$('edit-btn').classList.toggle('active',editing);$('edit-btn').innerHTML=editing?'✓ Finish editing':'<span aria-hidden="true">✎</span> Edit design';$('edit-bar').hidden=!editing;playing=false;updatePlay();};
all('[data-tool]').forEach(el=>el.onclick=()=>{tool=el.dataset.tool;all('[data-tool]').forEach(b=>b.classList.toggle('active',b===el));$('edit-hint').textContent=tool==='add'?'Click an empty roof area to add a panel.':'Drag a panel to reposition it on the roof.';});
$('rotate-panel').onclick=()=>{const p=currentPanels().find(p=>p.id===selected);if(!p)return toast('Select a panel first.');const candidate={...p,landscape:!p.landscape};if(!model.valid(candidate,currentPanels()))return toast('That orientation does not fit here. Move the panel first.');snapshot();Object.assign(p,candidate,{invalid:false});model.setPanels(currentPanels());recalculate();};
$('remove-panel').onclick=()=>{if(!selected)return toast('Select a panel first.');snapshot();layouts[layout]=currentPanels().filter(p=>p.id!==selected);model.setPanels(currentPanels());selectPanel(null);recalculate();};
$('undo-btn').onclick=()=>{const prev=history.pop();if(!prev)return toast('No edits to undo.');config=prev.config;layouts=prev.layouts;layout=prev.layout;buildSite(true);setLayout(layout);toast('Last edit undone.');};
$('reset-layout').onclick=()=>{snapshot();layouts[layout]=model.layouts()[layout];selectPanel(null);model.setPanels(currentPanels());recalculate();toast('This layout has been restored.');};
$('inspect-shade').onclick=()=>{const worst=Object.entries(current.per).sort((a,b)=>b[1].shade-a[1].shade)[0];if(worst){selectPanel(worst[0]);setLayer('shade');cameraPreset('roof');}};
const raycaster=new T.Raycaster(),pointer=new T.Vector2();function rayAt(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster;}
function panelHit(e){return rayAt(e).intersectObjects(model.panels.children,true).find(h=>h.object.userData.panelId);}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;clickStart={x:e.clientX,y:e.clientY};if(!editing||tool!=='move')return;const hit=panelHit(e);if(hit){const id=hit.object.userData.panelId,p=currentPanels().find(p=>p.id===id);selectPanel(id);drag={id,original:{...p},candidate:{...p},valid:!p.invalid,moved:false};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);}},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;if(Math.hypot(e.clientX-clickStart.x,e.clientY-clickStart.y)>3)drag.moved=true;if(!drag.moved)return;renderer.invalidate?.();const hit=rayAt(e).intersectObjects(model.roofMeshes,false)[0];if(hit){const p=model.localPanelFromPoint(hit.point,hit.object.userData.face,drag.original);drag.candidate=p;drag.valid=model.valid(p,currentPanels());const g=model.panelObjects.find(g=>g.userData.panelId===drag.id);g.position.copy(model.point(p));g.quaternion.copy(model.faces[p.face].q);g.userData.frame.material.color.set(drag.valid?0xffce77:0xff6655);}});
renderer.domElement.addEventListener('pointerup',e=>{if(drag){if(drag.moved&&drag.valid){snapshot();const p=currentPanels().find(p=>p.id===drag.id);Object.assign(p,drag.candidate,{invalid:false});recalculate();}else if(drag.moved)toast('Keep panels inside roof boundaries, clear of other panels and the front gable.');drag=null;controls.enabled=true;model.setPanels(currentPanels());updateInstant();return;}if(!clickStart||Math.hypot(e.clientX-clickStart.x,e.clientY-clickStart.y)>5)return;const hit=panelHit(e);if(hit){selectPanel(hit.object.userData.panelId);return;}if(editing&&tool==='add'){const roof=rayAt(e).intersectObjects(model.roofMeshes,false)[0];if(!roof)return toast('Click a roof surface.');const id='P'+String(Math.max(0,...currentPanels().map(p=>parseInt(p.id.slice(1))))+1).padStart(2,'0');const p=model.localPanelFromPoint(roof.point,roof.object.userData.face,{id,landscape:false});if(!model.valid(p,currentPanels()))return toast('Not enough clear roof area here. Try another position.');snapshot();currentPanels().push(p);model.setPanels(currentPanels());selectPanel(id);recalculate();}else selectPanel(null);});
renderer.domElement.addEventListener('pointercancel',()=>{if(drag){drag=null;controls.enabled=true;model.setPanels(currentPanels());updateInstant();}});
controls.addEventListener('start',()=>cameraTween=null);
function resize(){const r=$('scene').getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height);drawChart();}new ResizeObserver(resize).observe($('scene'));new ResizeObserver(drawChart).observe($('power-chart'));
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(cameraTween){const t=Math.min(1,(now-cameraTween.start)/cameraTween.duration),e=1-Math.pow(1-t,3);camera.position.lerpVectors(cameraTween.from,cameraTween.to,e);controls.target.lerpVectors(cameraTween.fromTarget,cameraTween.target,e);if(t===1)cameraTween=null;}controls.update();if(playing){hour+=dt*.48;if(hour>20)hour=6;if(now-lastSim>100){lastSim=now;updateInstant();}}if(loopCount++%2===0){const delta=camera.position.clone().sub(controls.target);const angle=Math.atan2(delta.x,delta.z)*180/Math.PI;$('compass').style.setProperty('--rot',angle+'deg');if(selected){const g=model.panelObjects.find(g=>g.userData.panelId===selected);if(g){const pos=g.getWorldPosition(new T.Vector3()).add(new T.Vector3(0,.4,0)).project(camera);const r=$('scene').getBoundingClientRect();$('panel-label').style.left=((pos.x*.5+.5)*r.width+8)+'px';$('panel-label').style.top=((-pos.y*.5+.5)*r.height-23)+'px';$('panel-label').hidden=pos.z>1||pos.z<-1;}}}renderer.render(scene,camera);}
function initWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const ac=new AbortController();window.addEventListener('pagehide',()=>ac.abort(),{once:true});const summary=()=>({layout,date,time:formatTime(hour),panelCount:validPanels(currentPanels()).length,powerKW:current.power,shadedPanels:current.shaded,dailyKWh:curves[layout]?.energy??null,bearing:config.bearing});for(const item of [{name:'read_solar_study',description:'Read the current visible solar study results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:summary},{name:'configure_solar_view',description:'Change the visible study layout, time, date or display layer. This changes the displayed simulation, not real equipment.',inputSchema:{type:'object',properties:{layout:{type:'string',enum:['A','B','C']},hour:{type:'number',minimum:6,maximum:20},date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},layer:{type:'string',enum:['realistic','shade','daily']}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['layout','hour','date','layer'].includes(k)))throw Error('Invalid settings');if(input.layout&&!['A','B','C'].includes(input.layout))throw Error('Invalid layout');if(input.layer&&!['realistic','shade','daily'].includes(input.layer))throw Error('Invalid layer');if(input.hour!==undefined&&(!Number.isFinite(input.hour)||input.hour<6||input.hour>20))throw Error('Time must be between 6 and 20');if(input.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||isNaN(new Date(input.date).getTime())))throw Error('Invalid date');playing=false;updatePlay();if(input.date){date=input.date;$('study-date').value=date;drawSunPath();recalculate();}if(input.hour!==undefined)hour=input.hour;if(input.layout)setLayout(input.layout);if(input.layer)setLayer(input.layer);updateInstant();if(input.date)await new Promise(r=>setTimeout(r,100));return summary();}}])try{Promise.resolve(ctx.registerTool(item,{signal:ac.signal})).catch(()=>{});}catch{}}
try{buildSite();cameraPreset('overview',true);setLayout('B');resize();if(renderer.compatibility){const badge=document.createElement('span');badge.className='compat-badge';badge.textContent='Compatibility view · simplified lighting';$('viewport').append(badge);}requestAnimationFrame(frame);initWebMCP();}catch(err){$('loading').innerHTML='The 3D view could not load. Please refresh or use a browser with WebGL enabled.';console.error(err);}
