import * as T from 'three';
import {buildArchitecture,tiledSurface,roofCaps} from './architecture.js';
export const rad=d=>d*Math.PI/180;
export const defaults={latitude:3.139,longitude:101.687,timezone:8,bearing:228,width:12,depth:16,eaves:7,pitch:30,treeHeight:5,treeX:4,treeDistance:7,neighbourHeight:6.5,neighbourDistance:7,panelWatts:450,panelWidth:1.13,panelLength:1.76,inverter:8,temperature:30};
export class BungalowModel{
 constructor(scene,config){this.scene=scene;this.config={...config};this.root=new T.Group();this.obstacles=[];this.roofMeshes=[];this.panels=new T.Group();this.panelObjects=[];this.overlay=new T.Group();scene.add(this.root);this.build();}
 box(w,h,d,x,y,z,mat,parent=this.root,obstacle=false,label='Building'){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;m.userData.label=label;parent.add(m);if(obstacle)this.obstacles.push(m);return m;}
 beam(a,b,r,mat,parent=this.root){const dir=new T.Vector3().subVectors(b,a);const m=new T.Mesh(new T.CylinderGeometry(r,r,dir.length(),8),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir.normalize());m.castShadow=true;parent.add(m);return m;}
 roofSpec(){const c=this.config;return {w:c.width+1,d:c.depth-2,z:-1};}
 build(){buildArchitecture(this);}
 makeHipRoof(cx,cz,w,d,y,pitch,mat,label,primary,detailed=false){const swap=w>d,sw=swap?d:w,sd=swap?w:d,rise=sw/2*Math.tan(pitch),rz=(sd-sw)/2;const v=[[-sw/2,y,sd/2],[sw/2,y,sd/2],[sw/2,y,-sd/2],[-sw/2,y,-sd/2],[0,y+rise,rz],[0,y+rise,-rz]].map(a=>new T.Vector3((swap?a[2]:a[0])+cx,a[1],(swap?a[0]:a[2])+cz));const faces=[[0,1,4],[1,2,5,4],[2,3,5],[3,0,4,5]];faces.forEach((arr,i)=>{const pts=[];for(let k=1;k<arr.length-1;k++)for(const idx of [arr[0],arr[k],arr[k+1]])pts.push(...v[idx].toArray());const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pts,3));g.computeVertexNormals();const m=new T.Mesh(g,mat);m.castShadow=m.receiveShadow=true;m.userData.label=label;m.userData.face=['front','right','back','left'][i];this.root.add(m);this.obstacles.push(m);if(primary)this.roofMeshes.push(m);if(primary||detailed)tiledSurface(this.root,arr.map(n=>v[n]),i*13+cz*7);});for(const [a,b]of [[0,4],[1,4],[2,5],[3,5],[4,5]]){if(primary||detailed)roofCaps(this,v[a],v[b]);else this.beam(v[a],v[b],.075,mat);}}
 makeGable(x,z,w,d,y,h,mat,label){const vv=[[-w/2,y,d/2],[0,y+h,d/2],[w/2,y,d/2],[-w/2,y,-d/2],[0,y+h,-d/2],[w/2,y,-d/2]].map(p=>new T.Vector3(p[0]+x,p[1],p[2]+z));for(const arr of [[0,3,4,1],[1,4,5,2],[0,1,2]]){const pts=[];for(let k=1;k<arr.length-1;k++)for(const idx of [arr[0],arr[k],arr[k+1]])pts.push(...vv[idx].toArray());const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pts,3));g.computeVertexNormals();const m=new T.Mesh(g,arr.length===3?new T.MeshStandardMaterial({color:0x594032,side:T.DoubleSide}):mat);m.castShadow=m.receiveShadow=true;m.userData.label=label;this.root.add(m);this.obstacles.push(m);if(arr.length===4)tiledSurface(this.root,arr.map(i=>vv[i]),17);}for(const [a,b]of [[1,4],[0,1],[1,2]])roofCaps(this,vv[a],vv[b],.085);}
 makeFaces(){const c=this.config,w=this.roofSpec().w,d=this.roofSpec().d,p=rad(c.pitch),s=Math.sin(p),co=Math.cos(p);const v=(x,y,z)=>new T.Vector3(x,y,z);this.faces={front:{origin:v(0,c.eaves,d/2),u:v(1,0,0),v:v(0,s,-co),n:v(0,co,s),length:w},right:{origin:v(w/2,c.eaves,0),u:v(0,0,-1),v:v(-co,s,0),n:v(s,co,0),length:d},back:{origin:v(0,c.eaves,-d/2),u:v(-1,0,0),v:v(0,s,co),n:v(0,co,-s),length:w},left:{origin:v(-w/2,c.eaves,0),u:v(0,0,1),v:v(co,s,0),n:v(-s,co,0),length:d}};Object.values(this.faces).forEach(f=>{f.origin.z+=this.roofSpec().z;f.q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(f.u,f.v,f.n));});}
 point(p,du=0,dv=0){const f=this.faces[p.face];return f.origin.clone().addScaledVector(f.u,p.u+du).addScaledVector(f.v,p.v+dv).addScaledVector(f.n,.12);}
 dimensions(p){return p.landscape?[this.config.panelLength,this.config.panelWidth]:[this.config.panelWidth,this.config.panelLength];}
 surfaceFits(p,du=0,dv=0,margin=.5){const f=this.faces[p.face];if(!f)return false;const c=this.config,spec=this.roofSpec(),hw=spec.w/2,hd=spec.d/2;const pos=f.origin.clone().addScaledVector(f.u,p.u+du).addScaledVector(f.v,p.v+dv);if(Math.abs(pos.x)>hw-margin||Math.abs(pos.z-spec.z)>hd-margin)return false;const height=c.eaves+Math.tan(rad(c.pitch))*Math.min(hw-Math.abs(pos.x),hd-Math.abs(pos.z-spec.z));if(Math.abs(height-pos.y)>.04)return false;const bayW=c.width*.43+.7,bayX=c.width*.27,bayFront=c.depth/2-.7;if(pos.x>bayX-bayW/2-.25&&pos.x<bayX+bayW/2+.25&&pos.z>bayFront-2.3)return false;const rw=c.width*.78,rd=5.9,rz=-c.depth/2+2.4;if(Math.abs(pos.x)<rw/2+.25&&Math.abs(pos.z-rz)<rd/2+.25){const rearHeight=c.eaves+.13+Math.tan(rad(27))*Math.min(rw/2-Math.abs(pos.x),rd/2-Math.abs(pos.z-rz));if(rearHeight>pos.y-.2)return false;}const hx=-c.width*.3,hz=-c.depth*.23;if(Math.abs(pos.x-hx)<.95&&Math.abs(pos.z-hz)<1.3)return false;return true;}
 valid(p,others=[]){const [w,h]=this.dimensions(p);for(const du of [-w/2,w/2])for(const dv of [-h/2,h/2])if(!this.surfaceFits(p,du,dv))return false;return !others.some(o=>{if(o.id===p.id||o.face!==p.face)return false;const [ow,oh]=this.dimensions(o);return Math.abs(o.u-p.u)<(w+ow)/2+.08&&Math.abs(o.v-p.v)<(h+oh)/2+.08;});}
 candidates(face){const f=this.faces[face],c=this.config,out=[];for(let row=0;row<4;row++){const v=.58/Math.cos(rad(c.pitch))+c.panelLength/2+row*(c.panelLength+.14);for(let col=0;col<20;col++){const u=-f.length/2+.6+c.panelWidth/2+col*(c.panelWidth+.12);const p={face,u,v,landscape:false};if(this.valid(p))out.push(p);}}return out;}
 layouts(){const a={front:this.candidates('front'),left:this.candidates('left'),right:this.candidates('right'),back:this.candidates('back')};const alternating=(lists,n)=>{let out=[],i=0;while(out.length<n&&lists.some(l=>i<l.length)){for(const l of lists)if(l[i]&&out.length<n)out.push({...l[i]});i++;}return out.map((p,i)=>({...p,id:'P'+String(i+1).padStart(2,'0')}));};const A=alternating([a.front,a.left,a.back,a.right],18);const B=alternating([a.right,[...a.front].reverse(),a.back,a.left],18);const occupied=new Set(B.map(p=>p.face+':'+p.u+':'+p.v));const extra=[...a.right,...a.back,...a.left,...a.front].filter(p=>!occupied.has(p.face+':'+p.u+':'+p.v));const C=[...B.map(p=>({...p})),...extra.slice(0,6).map((p,i)=>({...p,id:'P'+String(B.length+i+1).padStart(2,'0')}))];return {A,B,C};}
 setPanels(data){this.disposeGroup(this.panels);this.panelObjects=[];data.forEach(p=>{const [w,h]=this.dimensions(p);const g=new T.Group();g.position.copy(this.point(p));g.quaternion.copy(this.faces[p.face].q);const frame=new T.Mesh(new T.BoxGeometry(w,h,.065),new T.MeshStandardMaterial({color:0x93a5ae,metalness:.7,roughness:.4}));frame.castShadow=true;frame.userData.panelId=p.id;g.add(frame);const surface=new T.Mesh(new T.PlaneGeometry(w-.055,h-.055),new T.MeshStandardMaterial({color:0x173547,metalness:.34,roughness:.38,emissive:0x000000}));surface.position.z=.034;surface.userData.panelId=p.id;g.add(surface);const grid=new T.BufferGeometry(),lines=[];for(let i=1;i<6;i++){const x=-w/2+i*w/6;lines.push(x,-h/2+.025,.037,x,h/2-.025,.037);}for(let i=1;i<12;i++){const y=-h/2+i*h/12;lines.push(-w/2+.025,y,.037,w/2-.025,y,.037);}grid.setAttribute('position',new T.Float32BufferAttribute(lines,3));g.add(new T.LineSegments(grid,new T.LineBasicMaterial({color:0x7197a8,transparent:true,opacity:.28})));g.userData.panelId=p.id;g.userData.surface=surface;g.userData.frame=frame;this.panels.add(g);this.panelObjects.push(g);});this.root.updateMatrixWorld(true);}
 worldNormal(p){return this.faces[p.face].n.clone().transformDirection(this.root.matrixWorld);}
 worldPoint(p,du=0,dv=0){return this.root.localToWorld(this.point(p,du,dv));}
 localPanelFromPoint(point,face,base){const f=this.faces[face],v=this.root.worldToLocal(point.clone()).sub(f.origin);return {...base,face,u:Math.round(v.dot(f.u)*10)/10,v:Math.round(v.dot(f.v)*10)/10};}
 disposeGroup(group){while(group.children.length){const child=group.children[0];child.traverse(o=>{o.geometry?.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});group.remove(child);}}
 destroy(){this.disposeGroup(this.root);this.scene.remove(this.root);}
}
