import * as T from 'three';
import {rad} from './model.js';
const DEG=180/Math.PI;
export function sunPosition(date,hour,c){const dt=new Date(date+'T12:00:00Z'),start=Date.UTC(dt.getUTCFullYear(),0,0),day=Math.floor((dt-start)/86400000);const gamma=2*Math.PI/365*(day-1+(hour-12)/24);const eq=229.18*(.000075+.001868*Math.cos(gamma)-.032077*Math.sin(gamma)-.014615*Math.cos(2*gamma)-.040849*Math.sin(2*gamma));const decl=.006918-.399912*Math.cos(gamma)+.070257*Math.sin(gamma)-.006758*Math.cos(2*gamma)+.000907*Math.sin(2*gamma)-.002697*Math.cos(3*gamma)+.00148*Math.sin(3*gamma);const ha=rad((hour*60+eq+4*c.longitude-60*c.timezone)/4-180),lat=rad(c.latitude);const elev=Math.asin(Math.sin(lat)*Math.sin(decl)+Math.cos(lat)*Math.cos(decl)*Math.cos(ha));const az=(Math.atan2(Math.sin(ha),Math.cos(ha)*Math.sin(lat)-Math.tan(decl)*Math.cos(lat))*DEG+180+360)%360;const vec=new T.Vector3(Math.sin(rad(az))*Math.cos(elev),Math.sin(elev),-Math.cos(rad(az))*Math.cos(elev));return {elevation:elev*DEG,azimuth:az,direction:vec};}
const ray=new T.Raycaster();ray.near=.03;ray.far=120;
export function shadeAt(model,p,sun,samples=3){if(sun.elevation<=0)return {fraction:0,source:null};const [w,h]=model.dimensions(p);let blocked=0,counts={};for(let i=0;i<samples;i++)for(let j=0;j<samples;j++){const origin=model.worldPoint(p,((i+.5)/samples-.5)*w,((j+.5)/samples-.5)*h);ray.set(origin,sun.direction);const hits=ray.intersectObjects(model.obstacles,false);if(hits.length){blocked++;const name=hits[0].object.userData.label||'Roof geometry';counts[name]=(counts[name]||0)+1;}}return {fraction:blocked/(samples*samples),source:Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0]||null};}
export function irradiance(sun,normal){if(sun.elevation<=0)return {beam:0,diffuse:0,total:0};const alt=rad(sun.elevation),am=1/(Math.sin(alt)+.50572*Math.pow(sun.elevation+6.07995,-1.6364));const dni=1361*Math.pow(.7,Math.pow(am,.678));const dhi=90*Math.pow(Math.sin(alt),.5),ghi=dni*Math.sin(alt)+dhi;const beam=dni*Math.max(0,normal.dot(sun.direction));const diffuse=dhi*(1+normal.y)/2+ghi*.2*(1-normal.y)/2;return {beam,diffuse,total:beam+diffuse};}
export function estimate(model,panels,date,hour,c){const sun=sunPosition(date,hour,c);let dc=0,baselineDC=0,shaded=0;const per={};for(const p of panels){if(p.invalid)continue;const n=model.worldNormal(p),irr=irradiance(sun,n),shade=irr.beam>1?shadeAt(model,p,sun):{fraction:0,source:null};const received=irr.beam*(1-shade.fraction)+irr.diffuse;const watts=e=>Math.max(0,c.panelWatts*e/1000*(1-.0035*(c.temperature+e*.03-25))*.94);const power=watts(received),base=watts(irr.total);dc+=power;baselineDC+=base;if(shade.fraction>.01)shaded++;per[p.id]={shade:shade.fraction,source:shade.source,irradiance:received,dc:power,base,normal:n};}
const ac=Math.min(dc*.96/1000,c.inverter),unshaded=Math.min(baselineDC*.96/1000,c.inverter);return {sun,power:ac,baseline:unshaded,shaded,loss:unshaded>.005?Math.max(0,(1-ac/unshaded)*100):0,per};}
export function dailyCurve(model,panels,date,c){const data=[],panelEnergy={},panelSun={};let energy=0,baseEnergy=0,prev=null;for(let h=0;h<=24;h+=.25){const r=estimate(model,panels,date,h,c);data.push({hour:h,power:r.power,baseline:r.baseline,elevation:r.sun.elevation});if(prev){energy+=(prev.power+r.power)/2*.25;baseEnergy+=(prev.baseline+r.baseline)/2*.25;}for(const p of panels){const v=r.per[p.id];if(v){panelEnergy[p.id]=(panelEnergy[p.id]||0)+v.dc*.25/1000;panelSun[p.id]=(panelSun[p.id]||0)+(r.sun.elevation>0&&v.normal.dot(r.sun.direction)>0?(1-v.shade)*.25:0);}}prev=r;}return {data,energy,baseEnergy,loss:baseEnergy>0?100*(1-energy/baseEnergy):0,panelEnergy,panelSun};}
